sudo: false

language: generic

branches:
  only:
    - master

script: make test

before_cache:
 - rm -rf $HOME/.cache/pants/stats

cache:
  directories:
    - $HOME/.cache/pants
    - $TRAVIS_BUILD_DIR/.cache
