sudo: false

language: generic

branches:
  only:
    - master

script:
 - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && make test && make dist && .travis/deploy.sh

before_cache:
  - rm -rf $HOME/.cache/pants/stats

cache:
  directories:
    - $HOME/.cache/pants
    - $TRAVIS_BUILD_DIR/.cache

