
version: '3'

services:
  ## To allow continuous delivery via https://github.com/turbolent/deployd
  # deloyd:
  #  image: turbolent/deployd:latest
  #  environment:
  #    DEPLOYD_TOKEN: "SECRET"
  #  volumes:
  #    - type: bind
  #      source: "/var/run/docker.sock"
  #      target: "/var/run/docker.sock"
  #  deploy:
  #    placement:
  #      constraints: [node.role == manager]
  #  ports:
  #    - "7070:7070"

  api:
    image: turbolent/telescope-api:latest
    environment:
      ARGS: "-spacy-thrift-hostname=spacy-thrift -duckling-hostname=duckling"
    ports:
      - "8080:8080"

  spacy-thrift:
    image: turbolent/spacy-thrift
    ports:
      - "9090:9090"

  duckling:
    image: turbolent/duckling
    ports:
      - "8000:8000"

  debugger:
    image: turbolent/telescope-debugger:latest
    ports:
      - "7070:80"
