package com.turbolent.questionCompiler.sparql

trait NodeCompilationContext

case object TripleNodeCompilationContext extends NodeCompilationContext

case object FilterNodeCompilationContext extends NodeCompilationContext
